### ISSUE TITLE
Production build dont minifies js

### ISSUE THREAD

**Issue by foadyousefi** [dangvanthanh/vue-rollup-boilerplate#3]
This is very useful and simple build tool for non-SPA apps. 
But production build, don't minifies js. In line [43 of rollup.config.js](https://github.com/dangvanthanh/vue-rollup-boilerplate/blob/master/template/rollup.config.js#L43), you forgot to pass `butternut` as function, simply add `()` like:
`config.plugins.push(butternut())`

But anyway this is very helpful and useful.

**Comment by dangvanthanh** [comment]
@foadyousefi Thank you very much.

**Comment by foadyousefi** [comment]
Wow! very fast response. I liked it.
It is safe to close.
