### ISSUE TITLE
Enable Vue devtools

### ISSUE THREAD

**Issue by mikemcbride** [dangvanthanh/vue-rollup-boilerplate#7]
This template is awesome! Thanks a bunch for putting it together. As I was using it, I noticed I wasn't getting the Vue devtools because it was always building for production. I think it would be helpful to modify the rollup config to do something like this:

```js
replace({
    'process.env.NODE_ENV': production ? '"production"' : '"development"',
}),
```

Cheers!

**Comment by dangvanthanh** [comment]
Thank you very much @mikemcbride

**Comment by mikemcbride** [comment]
Anytime! Thanks for the quick response :)
